fix shlex.quote call on a PosixPath object
`shlex.quote` doesn't like a Path object, it only takes bytes or str objects:

```
    command = basecmd + shlex.quote(filepath)
                        ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/shlex.py", line 329, in quote
    if _find_unsafe(s) is None:
       ^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'PosixPath'
```