recitale: autogen: pass a string to glob.glob
glob.glob expects a string as parameter but was given a pathlib.Path
instead, resulting in some error like reported in
https://github.com/recitale/recitale/issues/16
or
TypeError: expected string or bytes-like object
Let's cast the pathlib.Path to a string before passing it to glob.glob
then.

Fixes #16
Fixes: 357c292c0bf5 ("recitale: migrate from path.py to pathlib")
Signed-off-by: Quentin Schulz <foss+recitale@0leil.net>